config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

class AdminConstraint
  def matches?(request)
    user_id = request.session[:user_id] || request.cookie_jar.encrypted[:user_id]

    User.find_by(id: user_id)&.admin_role?
  end
end

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    resource :session, only: %i[new create destroy]

    resource :password_reset, only: %i[new create edit update]

    resources :users, only: %i[new create edit update show] do
      resources :powers, except: %i[index]
      put '/powers/:id/update_power', to: 'powers#update_power', as: 'update_power'
      resources :crossfits, except: %i[index]
      put '/crossfits/:id/update_crossfit', to: 'crossfits#update_crossfit', as: 'update_crossfit'
      resources :gains, except: %i[index]
      put '/gains/:id/update_gain', to: 'gains#update_gain', as: 'update_gain'
      resources :photos, only: %i[index new create]
      resources :batmen, except: %i[index]
      put '/batmen/:id/update_batman', to: 'batmen#update_batman', as: 'update_batman'
      resources :wolverines, except: %i[index]
      put '/wolverines/:id/update_wolverine', to: 'wolverines#update_wolverine', as: 'update_wolverine'
      resources :spiders, except: %i[index]
      put '/spiders/:id/update_spider', to: 'spiders#update_spider', as: 'update_spider'
    end

    get '/faq', to: 'pages#faq'
    get '/training', to: 'pages#training'

    namespace :admin do
      resources :users, only: %i[index create edit update destroy]
    end
    root 'pages#index'
  end
end

app/models/power.rb
# frozen_string_literal: true

class Power < ApplicationRecord
  belongs_to :user

  validates :barbell_bench_press, presence: true
  validates :reverse_push_ups, presence: true
  validates :dumbbell_bench_press, presence: true
  validates :push_ups_on_bars, presence: true
  validates :stacked_chest_press, presence: true
  validates :extension_with_rope_handle, presence: true
  validates :dumbbell_abduction, presence: true
  validates :horizontal_pull_block, presence: true
  validates :pull_ups, presence: true
  validates :barbell_forearm_curls, presence: true
  validates :incline_dumbbell_row, presence: true
  validates :vertical_pull_block, presence: true
  validates :hyperextension, presence: true
  validates :hammers, presence: true
  validates :gack_squats, presence: true
  validates :seated_leg_extension, presence: true
  validates :leg_press, presence: true
  validates :hamer_shoulder_press, presence: true
  validates :dumbbells_through_the_side, presence: true
  validates :lying_leg_flexion, presence: true
  validates :pancake_swing_in_front_of_you, presence: true
  validates :barbell_pull_to_chin, presence: true
end

app/controllers/powers_controller.rb
# frozen_string_literal: true

class PowersController < ApplicationController
  before_action :set_user
  before_action :set_power, except: %i[new create]

  def show; end

  def new
    @power = @user.powers.build
  end

  def edit; end

  def create
    @power = @user.powers.build power_params
    if @power.save
      flash[:success] = t('.success')
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def update
    if @power.update power_params
      flash[:success] = t('.success')
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def update_power
    case params[:complete_training]
    when 'fail'
      flash[:success] = t('.fail')
    when 'monday'
      if current_training.monday_reps <= 9
        pump_reps_monday
      else
        pump_reps_monday
        pump_power_monday
      end
      flash[:success] = t('.success')
    when 'wednesday'
      if current_training.wednesday_reps <= 9
        pump_reps_wednesday
      else
        pump_reps_wednesday
        pump_power_wednesday
      end
      flash[:success] = t('.success')
    when 'friday'
      if current_training.friday_reps <= 9
        pump_reps_friday
      else
        pump_reps_friday
        pump_power_friday
      end
      pump_count_update_training
      flash[:success] = t('.success')
    end
    redirect_to root_path
  end

  def destroy
    @power.destroy
    flash[:success] = t('.success')
    redirect_to user_path(@user)
  end

  private

  def set_user
    @user = User.find params[:user_id]
  end

  def set_power
    @power = @user.powers.find params[:id]
  end

  def power_params
    params.require(:power).permit(:barbell_bench_press, :reverse_push_ups, :dumbbell_bench_press, :push_ups_on_bars,
                                  :stacked_chest_press, :extension_with_rope_handle, :dumbbell_abduction,
                                  :horizontal_pull_block, :pull_ups, :barbell_forearm_curls, :incline_dumbbell_row,
                                  :vertical_pull_block, :hyperextension, :hammers, :gack_squats, :seated_leg_extension,
                                  :leg_press, :hamer_shoulder_press, :dumbbells_through_the_side,
                                  :lying_leg_flexion, :pancake_swing_in_front_of_you, :barbell_pull_to_chin)
  end
end

app/views/powers/_friday.html.erb
<h3 class="my-4 center", style="color:#ffffff">
  <strong><% t('global.dropdown.monday') %></strong>
</h3> 

<body style="color:#ffffff">
  <div class="container my-4">
    <div class="row row-cols-4 center">
      <div class="col"><strong><%= t('views.exercise')%></strong></div>
      <div class="col"><strong><%= t('views.count_sets')%></strong></div>
      <div class="col"><strong><%= t('views.count_reps')%></strong></div>
      <div class="col"><strong><%= t('views.weight')%></strong></div>
    </div>
    <div class="row row-cols-4 my-3 center">
      <div class="col">
        <button class="btn btn-outline-light" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapseText" aria-expanded="false"
                aria-controls="collapseText"><%= t('activerecord.attributes.gain.gack_squats') %>
        </button>
        <div class="collapse my-2" id="collapseText">
          <span>
            <%= image_tag('Гакк приседания.jpeg') %>
            <ul>
              <li>Прижмите спину и плечи к тренажёру.</li>
              <li>Поставьте ноги на середину платформы на ширине плеч, носки разведите немного наружу.</li>
              <li>Выпрямите колени, но не до конца.</li>
              <li>Со вдохом присядьте до параллели бёдер с полом.</li>
              <li>С выдохом надавите пятками и выжмите себя вверх.</li>
            </ul>
          </span>
        </div>
      </div>
      <div class="col">4</div>
      <div class="col"><%= current_training.friday_reps %></div>
      <div class="col"><%= current_training.gack_squats.ceil%> кг.</div>
    </div>
    <div class="row row-cols-4 my-3 center">
      <div class="col">
        <button class="btn btn-outline-light" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapseText1" aria-expanded="false"
                aria-controls="collapseText1"><%= t('activerecord.attributes.gain.seated_leg_extension') %>
        </button>
        <div class="collapse my-2" id="collapseText1">
          <span>
            <%= image_tag('Разгибания голени сидя.jpeg') %>
            <ul>
              <li>Сядьте в тренажер, прижмитесь спиной к его спинке и заведите ноги за валик.</li>
              <li>Руками возьмитесь за специальные ручки по бокам от сиденья.</li>
              <li>Носки стоп поднимите вверх.</li>
              <li>На выдохе плавно разогните ноги в коленях.</li>
              <li>Максимально напрягите квадрицепсы в верхней точке, задержитесь в таком положении на 1–2 секунды.</li>
              <li>На вдохе подконтрольно опустите ноги вниз, но не сгибайте их до конца.</li>
              <li>То есть даже в нижней точке квадрицепсы должны быть напряжены.</li>
              <li>Следите за ощущениями в коленях, не бросайте резко ноги вниз.</li>
            </ul>
          </span>
        </div>
      </div>
      <div class="col">4</div>
      <div class="col"><%= current_training.friday_reps %></div>
      <div class="col"><%= current_training.seated_leg_extension.ceil%> кг.</div>
    </div>
    <div class="row row-cols-4 my-3 center">
      <div class="col">
        <button class="btn btn-outline-light" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapseText2" aria-expanded="false"
                aria-controls="collapseText2"><%= t('activerecord.attributes.gain.leg_press') %>
        </button>
        <div class="collapse my-2" id="collapseText2">
          <span>
            <%= image_tag('Жим ногами.jpeg') %>
            <ul>
              <li>Займите исходную позицию: стопы ставят на платформу, поясницу прижимают к скамье.</li>
              <li>Убрерите фиксаторы отягощения с помощью рычагов.</li>
              <li>На вдохе опустите платформу, согнув ноги в коленях.</li>
              <li>В нижней точке ноги образуют угол 90 градусов.</li>
              <li>На выдохе вытолкните ногами платформу вверх.</li>
            </ul>
          </span>
        </div>
      </div>
      <div class="col">4</div>
      <div class="col"><%= current_training.friday_reps %></div>
      <div class="col"><%= current_training.leg_press.ceil%> кг.</div>
    </div>
    <div class="row row-cols-4 my-3 center">
      <div class="col">
        <button class="btn btn-outline-light" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapseText3" aria-expanded="false"
                aria-controls="collapseText3"><%= t('activerecord.attributes.gain.hamer_shoulder_press') %>
        </button>
        <div class="collapse my-2" id="collapseText3">
          <span>
            <%= image_tag('Жим в хамере на плечи.jpeg') %>
            <ul>
              <li>Тренажер нужно отрегулировать под свой рост.</li>
              <li>Бедра должны быть параллельны полу.</li>
              <li>Рукоятки находятся чуть выше плечевых суставов так, чтобы хват был комфортным.</li>
              <li>Садимся прямо, живот втягиваем, воздух набираем в грудную клетку, и спину прижимаем к спинке тренажера.</li>
              <li>Важно чтобы на старте плечи не были подведены к ушам, а лопатки были сведены и опущены к тазу.</li>
              <li>На выдохе выполняется разгибание в плечевых и локтевых суставах, жим вверх.</li>
              <li>На вдохе рукоятка опускается в исходное положение, грудная клетка опускается.</li>
            </ul>
          </span>
        </div>
      </div>
      <div class="col">4</div>
      <div class="col"><%= current_training.friday_reps %></div>
      <div class="col"><%= current_training.hamer_shoulder_press.ceil%> кг.</div>
    </div>
    <div class="row row-cols-4 my-3 center">
      <div class="col">
        <button class="btn btn-outline-light" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapseText4" aria-expanded="false"
                aria-controls="collapseText4"><%= t('activerecord.attributes.gain.dumbbells_through_the_side') %>
        </button>
        <div class="collapse my-2" id="collapseText4">
          <span>
            <%= image_tag('Махи гантелей через сторону.jpeg') %>
            <ul>
              <li>Встаньте прямо, ноги на ширине плеч.</li>
              <li>Возьмите гантели и держите их нейтральным хватом, чтобы руки были ладонями друг к другу.</li>
              <li>Руки в локтях слегка согнуты - этот угол нужно удерживать на всей амплитуде, это очень важно.</li>
              <li>Гантелями не касаемся друг друга, кисти строго под плечами, но не ближе.</li>
              <li>Сделайте чуть заметный наклон корпуса вперед ровно настолько, чтобы гантели расположились перед вами.</li>
              <li>На выдохе начинайте отводить руки в стороны и поднимайте гантели, но не выше уровня плеч.</li>
              <li>Гантели должны быть параллельны земле, кисти не поворачиваем.</li>
              <li>В верхней точке мы стараемся поднять именно локти, как в тяге гантелей к подбородку.</li>
              <li>На вдохе медленно верните гантели в исходное положение, но в нижней точке не касайтесь гантелями друг друга!</li>
            </ul>
          </span>
        </div>
      </div>
      <div class="col">4</div>
      <div class="col"><%= current_training.friday_reps %></div>
      <div class="col"><%= current_training.dumbbells_through_the_side.ceil%> кг.</div>
    </div>
    <div class="row row-cols-4 my-3 center">
      <div class="col">
        <button class="btn btn-outline-light" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapseText5" aria-expanded="false"
                aria-controls="collapseText5"><%= t('activerecord.attributes.gain.lying_leg_flexion') %>
        </button>
        <div class="collapse my-2" id="collapseText5">
          <span>
            <%= image_tag('Сгибание голени лежа.jpeg') %>
            <ul>
              <li>Лягте на тренажер и заведите ноги под валик.</li>
              <li>Руками возьмитесь за специальные ручки или за края скамьи.</li>
              <li>На выдохе согните голени, стараясь максимально приблизить валик к ягодицам.</li>
              <li>Передняя поверхность бедер при этом прижата к скамье.</li>
              <li>На вдохе разгибайте голени, аккуратно опуская вес вниз.</li>
              <li>Полностью выпрямлять колени и расслаблять бицепс бедра в нижней точке не нужно.</li>
            </ul>
          </span>
        </div>
      </div>
      <div class="col">4</div>
      <div class="col"><%= current_training.friday_reps %></div>
      <div class="col"><%= current_training.lying_leg_flexion.ceil%> кг.</div>
    </div>
    <div class="row row-cols-4 my-3 center">
      <div class="col">
        <button class="btn btn-outline-light" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapseText6" aria-expanded="false"
                aria-controls="collapseText6"><%= t('activerecord.attributes.gain.pancake_swing_in_front_of_you') %>
        </button>
        <div class="collapse my-2" id="collapseText6">
          <span>
            <%= image_tag('Мах блина перед собой.jpeg') %>
            <ul>
              <li>Встаньте прямо.</li>
              <li>Представьте себе, что блин – это циферблат.</li>
              <li>Ваша задача взять его таким образом, чтобы ладони были на 3 и 9 часов.</li>
              <li>Держите его в опущенных вниз, немного согнутых в локтях руках.</li>
              <li>На выдохе, медленно поднимите блин немного выше уровня плеч.</li>
              <li>Задержитесь на секунду.</li>
              <li>Не допускайте рывков и не сгибайте локти. Корпус неподвижен.</li>
              <li>На вдохе также медленно опускайте вес в исходное положение.</li>
            </ul>
          </span>
        </div>
      </div>
      <div class="col">4</div>
      <div class="col"><%= current_training.friday_reps %></div>
      <div class="col"><%= current_training.pancake_swing_in_front_of_you.ceil%> кг.</div>
    </div>
    <div class="row row-cols-4 my-3 center">
      <div class="col">
        <button class="btn btn-outline-light" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapseText7" aria-expanded="false"
                aria-controls="collapseText7"><%= t('activerecord.attributes.gain.barbell_pull_to_chin') %>
        </button>
        <div class="collapse my-2" id="collapseText7">
          <span>
            <%= image_tag('Тяга штанги к подбородку.jpeg') %>
            <ul>
              <li>Держите штангу верхним хватом (промежуток между ладонями немного меньше ширины плеч) и выровняйтесь.</li>
              <li>В исходном положении спина прямая и чуть прогнута в пояснице, плечи расправлены, руки в локтях ровные, гриф слегка касается бедер.</li>
              <li>Вдохните и, задержав дыхание, напрягите дельту и трапецепидную.</li>
              <li>Разведите локти и потяните их вверх вертикально.</li>
              <li>Движение «направляют» именно локти, а не предплечья или плечи.</li>
              <li>Когда вы поднимаете локти вверх, гриф штанги должен двигаться в вертикальной плоскости в длину тела от подбородка до бедер.</li>
              <li>Не нависайте над грифом, прогибая спину.</li>
              <li>Держите тело и шею прямо, а подбородок — горизонтально.</li>
              <li>В верхней точке локти находятся максимально вверху.</li>
              <li>Дотянувшись до верхней точки, сделайте выдох, остановитесь и еще больше напрягите дельты и трапеции.</li>
              <li>Медленно опустите гриф в исходное положение.</li>
            </ul>
          </span>
        </div>
      </div>
      <div class="col">4</div>
      <div class="col"><%= current_training.friday_reps %></div>
      <div class="col"><%= current_training.barbell_pull_to_chin.ceil%> кг.</div>
    </div>
    <div class="row row-cols-4 my-3 center">
      <div class="col">
         <button class="btn btn-outline-light" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapseText8" aria-expanded="false"
                aria-controls="collapseText8"><%= t('activerecord.attributes.gain.hanging_leg_raise') %>
        </button>
        <div class="collapse my-2" id="collapseText8">
          <span>
            <%= image_tag('Подъем ног в висе.jpeg') %>
            <ul>
              <li>Расположитесь на брусьях в положении свободного виса, опираясь на согнутые в локтях руки.</li>
              <li>Напрягая пресс, поднимите согнутые в коленях ноги до горизонтального уровня.</li>
              <li>Задержавшись на несколько секунд, вернитесь в исходное положение.</li>
            </ul>
          </span>
        </div>
      </div>
      <div class="col">4</div>
      <div class="col">30</div>
      <div class="col"><%= current_training.hanging_leg_raise.ceil%> кг.</div>
    </div>
  </div>
  </div>

  <div class="row row-cols-2 my-5">
    <div class="col left">
      <%= link_to t('global.button.fail'), user_update_power_path(@user, @power, complete_training: 'fail'), method: :put,
        class: 'btn btn-danger btn-lg'%></div>

    <div class="col right"><%= link_to t('global.button.complete'), user_update_power_path(@user, @power, complete_training: 'friday'), method: :put,
      class: 'btn btn-success btn-lg'%></div>
  </div>
</body>

app/views/powers/_train.html.erb
<div class="progress">
  <div class="progress-bar bg-dark progress-bar-striped progress-bar-animated" role="progressbar"
       style="width: <%= current_training.count_update_training * 2%>%"
       aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">
       <%= current_training.count_update_training * 2%>%
  </div>
</div>

<div class="dropdown center my-3">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
    <%= t('global.dropdown.change_training')%>
  </button>
  <ul class="dropdown-menu">
    <li>
      <%= link_to t('global.dropdown.monday'), user_power_path(@user, @power, day: 'monday'),
        class: 'dropdown-item'%>
    </li>

    <li><hr class="dropdown-divider"></li>

    <li>
      <%= link_to t('global.dropdown.wednesday'), user_power_path(@user, @power, day: 'wednesday'),
        class: 'dropdown-item'%>
    </li>

    <li><hr class="dropdown-divider"></li>

    <li>
      <%= link_to t('global.dropdown.friday'), user_power_path(@user, @power, day: 'friday'),
        class: 'dropdown-item'%>
    </li>
  </ul>
</div>

<% case params[:day] %>
  <% when 'monday'%>
    <%= render 'monday' %>
  <% when 'wednesday'%>
    <%= render 'wednesday' %>
  <% when 'friday'%>
    <%= render 'friday' %>
<% end %>

app/views/powers/edit.html.erb
<% provide :page_title, t('powers.edit.title') %>
<% currently_at t('powers.edit.title') %>
<h1 class="center"><%= t('powers.edit.title') %></h1>

<%= render 'form' %>

app/views/powers/new.html.erb
<% provide :page_title, t('.title') %>
<% currently_at t('menu.title') %>

<h1 class="mb-4 center"><%= t('.title') %></h1>

<%= render 'form' %>

app/views/powers/show.html.erb
<% provide :page_title, t('.title') %>
<% currently_at t('menu.powers') %>

<body class="my-black-fon">

  <h1 class="center", style="color:#ffffff"><%= t('menu.powers')%></h1>
  <%= render 'train'%>
</body>