config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

class AdminConstraint
  def matches?(request)
    user_id = request.session[:user_id] || request.cookie_jar.encrypted[:user_id]

    User.find_by(id: user_id)&.admin_role?
  end
end

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    resource :session, only: %i[new create destroy]

    resource :password_reset, only: %i[new create edit update]

    resources :users, only: %i[new create edit update show] do
      resources :powers, except: %i[index]
      put '/powers/:id/update_power', to: 'powers#update_power', as: 'update_power'
      resources :crossfits, except: %i[index]
      put '/crossfits/:id/update_crossfit', to: 'crossfits#update_crossfit', as: 'update_crossfit'
      resources :gains, except: %i[index]
      put '/gains/:id/update_gain', to: 'gains#update_gain', as: 'update_gain'
      resources :photos, only: %i[index new create]
      resources :batmen, except: %i[index]
      put '/batmen/:id/update_batman', to: 'batmen#update_batman', as: 'update_batman'
      resources :wolverines, except: %i[index]
      put '/wolverines/:id/update_wolverine', to: 'wolverines#update_wolverine', as: 'update_wolverine'
      resources :spiders, except: %i[index]
      put '/spiders/:id/update_spider', to: 'spiders#update_spider', as: 'update_spider'
    end

    get '/faq', to: 'pages#faq'
    get '/training', to: 'pages#training'

    namespace :admin do
      resources :users, only: %i[index create edit update destroy]
    end
    root 'pages#index'
  end
end

app/models/spider.rb
class Spider < ApplicationRecord
  belongs_to :user

  validates :barbell_bench_press, presence: true
  validates :incline_press, presence: true
  validates :push_ups_on_bars, presence: true
  validates :close_grip_bench_press, presence: true
  validates :seated_dumbbell_press, presence: true
  validates :barbell_pull_to_chin, presence: true
  validates :deadlift, presence: true
  validates :pull_ups, presence: true
  validates :incline_dumbbell_row, presence: true
  validates :horizontal_pull_block, presence: true
  validates :barbell_forearm_curls, presence: true
  validates :squats, presence: true
  validates :leg_press, presence: true
  validates :romanian_deadlift, presence: true
  validates :lunges, presence: true
  validates :standing_calf_raises, presence: true
end

app/controllers/spiders_controller.rb
# frozen_string_literal: true

class SpidersController < ApplicationController
  before_action :set_user
  before_action :set_spider, except: %i[new create]

  def show; end

  def new
    @spider = @user.spiders.build
  end

  def create
    @spider = @user.spiders.build spider_params
    if @spider.save
      flash[:success] = t('.success')
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def update_spider
    case params[:complete_training]
    when 'fail'
      flash[:success] = t('.fail')
    when 'monday'
      if current_spider_training.monday_reps <= 9
        pump_monday_reps
      else
        pump_monday_reps
        pump_spider_monday
      end
      flash[:success] = t('.success')
    when 'wednesday'
      if current_spider_training.wednesday_reps <= 9
        pump_wednesday_reps
      else
        pump_wednesday_reps
        pump_spider_wednesday
      end
      flash[:success] = t('.success')
    when 'friday'
      if current_spider_training.friday_reps <= 9
        pump_friday_reps
      else
        pump_friday_reps
        pump_spider_friday
      end
      pump_count_update_training
      flash[:success] = t('.success')
    end
    redirect_to root_path
  end

  private

  def set_user
    @user = User.find params[:user_id]
  end

  def set_spider
    @spider = @user.spiders.find params[:id]
  end

  def spider_params
    params.require(:spider).permit(:barbell_bench_press, :incline_press, :push_ups_on_bars,
                                   :close_grip_bench_press, :seated_dumbbell_press, :barbell_pull_to_chin,
                                   :deadlift, :pull_ups, :incline_dumbbell_row, :horizontal_pull_block,
                                   :barbell_forearm_curls, :squats, :leg_press,
                                   :romanian_deadlift, :lunges, :standing_calf_raises, :sitap, :book)
  end
end

app/views/spiders/_friday.html.erb
<h3 class="my-4 center"><strong><%= t('activerecord.attributes.models.spider')%></strong></h3>
  <div class="container my-4">
    <div class="row row-cols-4 center">
      <div class="col"><strong><%= t('views.exercise')%></strong></div>
      <div class="col"><strong><%= t('views.count_sets')%></strong></div>
      <div class="col"><strong><%= t('views.count_reps')%></strong></div>
      <div class="col"><strong><%= t('views.weight')%></strong></div>
    </div>
        
    <div class="row row-cols-4 my-3 center">
      <div class="col">
        <button class="btn btn-outline-light" type="button" data-bs-toggle="collapse"
              data-bs-target="#collapseText1" aria-expanded="false"
              aria-controls="collapseText1"><%= t('activerecord.attributes.spider.squats') %>
        </button>
        <div class="collapse my-2" id="collapseText1">
          <span>
            <%= image_tag('Приседания со штангой.jpeg') %>
            <ul>
              <li>Возьмите гриф прямым закрытым хватом за плечами</li>
              <li>Спину держите прямо, лопатки сведите.</li>
              <li>После снятия штанги со стойки и перед приседом нужно максимально сконцентрироваться, сохраняя равновесие.</li>
              <li>Поставьте стопы шире плеч и слегка разведите носки в стороны.</li>
              <li>На вдохе отводите таз назад и разводите колени в стороны.</li>
              <li>Спина сохраняет естественное положение.</li>
              <li>Со стороны это выглядит так, будто вы садитесь на невидимый стул.</li>
              <li>На выдохе поднимайтесь из максимальной точки приседа вверх.</li>
              <li>Сохраняйте спину ровной, поднимая тело за счет выпрямления ног.</li>
            </ul>
          </span>
        </div>
      </div>
      <div class="col">4</div>
      <div class="col"><%= current_spider_training.friday_reps %></div>
      <div class="col"><%= current_spider_training.squats.ceil%> кг.</div>
    </div>
    <div class="row row-cols-4 my-3 center">
      <div class="col">
        <button class="btn btn-outline-light" type="button" data-bs-toggle="collapse"
              data-bs-target="#collapseText3" aria-expanded="false"
              aria-controls="collapseText3"><%= t('activerecord.attributes.spider.leg_press') %>
        </button>
          <div class="collapse my-2" id="collapseText3">
            <span>
              <%= image_tag('Жим ногами.jpeg') %>
              <ul>
                <li>Займите исходную позицию: стопы ставят на платформу, поясницу прижимают к скамье.</li>
                <li>Убрерите фиксаторы отягощения с помощью рычагов.</li>
                <li>На вдохе опустите платформу, согнув ноги в коленях.</li>
                <li>В нижней точке ноги образуют угол 90 градусов.</li>
                <li>На выдохе вытолкните ногами платформу вверх.</li>
              </ul>
            </span>
        </div>
      </div>
      <div class="col">4</div>
      <div class="col"><%= current_spider_training.friday_reps %></div>
      <div class="col"><%= current_spider_training.leg_press.ceil%> кг.</div>
    </div>
    <div class="row row-cols-4 my-3 center">
      <div class="col">
        <button class="btn btn-outline-light" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapseText4" aria-expanded="false"
                aria-controls="collapseText4"><%= t('activerecord.attributes.spider.romanian_deadlift') %>
        </button>
        <div class="collapse my-2" id="collapseText4">
          <span>
            <%= image_tag('Румынская тяга.jpeg') %>
            <ul>
              <li>Исходное положение — встаньте прямо, ноги на ширине бедер.</li>
              <li>Сделайте глубокий вдох и наклоняйся вперед, пока штанга не окажется на уровне середины голени.</li>
              <li>Гриф штанги должен двигаться вниз очень близко к передней поверхности ног, почти гладить их.</li>
              <li>Помните, что опускать штангу необходимо не наклоном вперед кора, а отведением таза назад.</li>
              <li>Сделайте внизу паузу на секунду, и на выдохе вытолкните себя в исходное положение бицепсами бедра и ягодичными мышцами.</li>
            </ul>
          </span>
        </div>
      </div>
      <div class="col">4</div>
      <div class="col"><%= current_spider_training.friday_reps %></div>
      <div class="col"><%= current_spider_training.romanian_deadlift.ceil%> кг.</div>
    </div>
    <div class="row row-cols-4 my-3 center">
      <div class="col">
        <button class="btn btn-outline-light" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapseText5" aria-expanded="false"
                aria-controls="collapseText5"><%= t('activerecord.attributes.spider.lunges') %>
        </button>
        <div class="collapse my-2" id="collapseText5">
          <span>
            <%= image_tag('Выпады.jpeg') %>
            <ul>
              <li>Возьмите пару гантелей, встаньте прямо, слегка согнув ноги в коленях.</li>
              <li>Опустите руки с гантелями вниз по бокам.</li>
              <li>Теперь Вы в исходном положении.</li>
              <li>Сделайте шаг вперед левой ногой сохраняя равновесие, и присядьте вниз с помощью мышц бедра.</li>
              <li>Держите торс прямо, сохраняя напряжение.</li>
              <li>Не позволяйте колену левой ноги заходить за линию пальцев левой ноги.</li>
              <li>Вернитесь в исходное положение, оттолкнувшись левой ногой.</li>
              <li>Повторите движение с правой ноги.</li>
            </ul>
          </span>
        </div>
      </div>
      <div class="col">4</div>
      <div class="col"><%= current_spider_training.friday_reps %></div>
      <div class="col"><%= current_spider_training.lunges.ceil%> кг.</div>
    </div>

    <div class="row row-cols-4 my-3 center">
      <div class="col">
        <button class="btn btn-outline-light" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapseText6" aria-expanded="false"
                aria-controls="collapseText6"><%= t('activerecord.attributes.spider.standing_calf_raises') %>
        </button>
        <div class="collapse my-2" id="collapseText6">
          <span>
            <%= image_tag('Подъемы на носки стоя.jpeg') %>
            <ul>
              <li>Возьмите гантели в руки.</li>
              <li>Полностью выпрямите ноги и торс.</li>
              <li>Пятки, таз и плечи находятся в одной вертикальной плоскости.</li>
              <li>Разгибая голеностопный сустав, плавно опуститесь на пятках до тех пор, пока не почувствуете, что ахиллесовы икроножные мышцы максимально растянуты.</li>
              <li>Вернитесь в исходное положение</li>
            </ul>
          </span>
        </div>
      </div>
      <div class="col">4</div>
      <div class="col"><%= current_spider_training.friday_reps %></div>
      <div class="col"><%= current_spider_training.standing_calf_raises.ceil%> кг.</div>
    </div>

    <div class="row row-cols-4 my-3 center">
      <div class="col">
        <button class="btn btn-outline-light" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapseText7" aria-expanded="false"
                aria-controls="collapseText7"><%= t('activerecord.attributes.batman.sitap') %>
        </button>
        <div class="collapse my-2" id="collapseText7">
          <span>
            <%= image_tag('Ситап.jpeg') %>
            <ul>
              <li>Лягте на пол.</li>
              <li>Согните ноги в коленях и поставьте стопы на пол по ширине таза.</li>
              <li>Не слишком близко к тазу.</li>
              <li>Заведите прямые руки назад и коснитесь тыльной стороной кисти пола.</li>
              <li>С выдохом поднимите корпус, округляя позвоночник, и коснитесь ладонями стоп.</li>
              <li>Затем плавно без падения опуститесь на пол, заведя руки за голову, касаясь ими пола.</li>
            </ul>
          </span>
        </div>
      </div>
      <div class="col">4</div>
      <div class="col">25</div>
      <div class="col">0 кг.</div>
    </div>

    <div class="row row-cols-4 my-3 center">
      <div class="col">
        <button class="btn btn-outline-light" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapseText8" aria-expanded="false"
                aria-controls="collapseText8"><%= t('activerecord.attributes.batman.book') %>
        </button>
        <div class="collapse my-2" id="collapseText8">
          <span>
            <%= image_tag('Книжка.jpeg') %>
            <ul>
              <li>Садитесь на край лавки.</li>
              <li>Сведите ноги вместе и выставите вперед со слегка согнутыми коленями.</li>
              <li>Руками упритесь в край скамьи и отклоните корпус назад.</li>
              <li>Поднимайте ноги, сгибайте их в коленях и подтягивайте к себе.</li>
              <li>Одновременно подавайте корпус вперед (грудь движется на встречу коленям).</li>
              <li>Сделайте паузу на 1 секунду на выдохе, после чего вернитесь в исходную позицию.</li>
            </ul>
          </span>
        </div>
      </div>
      <div class="col">4</div>
      <div class="col">25</div>
      <div class="col">0 кг.</div>
    </div>

    <div class="row row-cols-2 my-5">
      <div class="col left">
        <%= link_to t('global.button.fail'), user_update_spider_path(@user, @spider, complete_training: 'fail'), method: :put,
          class: 'btn btn-danger btn-lg'%></div>

      <div class="col right"><%= link_to t('global.button.complete'), user_update_spider_path(@user, @spider, complete_training: 'friday'), method: :put,
        class: 'btn btn-success btn-lg'%></div>
    </div>
  </div>

app/views/spiders/_monday.html.erb
<h3 class="my-4 center"><strong><%= t('activerecord.attributes.models.spider')%></strong></h3>
  <div class="container my-4">
    <div class="row row-cols-4 center">
      <div class="col"><strong><%= t('views.exercise')%></strong></div>
      <div class="col"><strong><%= t('views.count_sets')%></strong></div>
      <div class="col"><strong><%= t('views.count_reps')%></strong></div>
      <div class="col"><strong><%= t('views.weight')%></strong></div>
    </div>
    <div class="row row-cols-4 my-3 center">
      <div class="col">
        <button class="btn btn-outline-light" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapseText" aria-expanded="false"
                aria-controls="collapseText"><%= t('activerecord.attributes.spider.barbell_bench_press') %>
        </button>
        <div class="collapse my-2" id="collapseText">
          <span>
            <%= image_tag('Жим лежа.jpeg') %>
            <ul>
              <li>Лягте на скамью, поставив ступни на пол и согнув колени.</li>
              <li>Держите спину прямо, голову вверх.</li>
              <li>Держите штангу перед грудью.</li>
              <li>Сожмите лопатки вместе.</li>
              <li>Опускайте штангу вниз, пока она не коснется верхней части груди.</li>
              <li>Сделайте паузу, затем снова поднимите штангу.</li>
            </ul>
          </span>
        </div>
      </div>
      <div class="col">4</div>
      <div class="col"><%= current_spider_training.monday_reps %></div>
      <div class="col"><%= current_spider_training.barbell_bench_press.ceil%> кг.</div>
    </div>
    <div class="row row-cols-4 my-3 center">
      <div class="col">
        <button class="btn btn-outline-light" type="button" data-bs-toggle="collapse"
              data-bs-target="#collapseText1" aria-expanded="false"
              aria-controls="collapseText1"><%= t('activerecord.attributes.spider.incline_press') %>
        </button>
        <div class="collapse my-2" id="collapseText1">
          <span>
            <%= image_tag('жим на наклонной скамье.jpeg') %>
            <ul>
              <li>Установите нужный угол спинки скамьи. Сядьте на нее так, чтобы таз был прижат к сиденью, а спина к спинке.</li>
              <li>Ноги расставьте в стороны и упритесь пятками в пол.</li>
              <li>В пояснице оставьте естественный прогиб.</li>
              <li>Лопатки сведите, они должны упираться в спинку.</li>
              <li>Голову положите на спинку, смотрите на верх противоположной вам стены.</li>
              <li>Возьмитесь за гриф прямым хватом шире плеч, ориентируясь по рискам.</li>
              <li>Снимите гриф со стоек, выведите его на исходную позицию: он должен расположиться над вашими ключицами.</li>
              <li>Опустите гриф на верх груди на вдохе.</li>
              <li>Не задерживая дыхания, выдыхайте и толкайте штангу вверх.</li>
            </ul>
          </span>
        </div>
      </div>
      <div class="col">4</div>
      <div class="col"><%= current_spider_training.monday_reps %></div>
      <div class="col"><%= current_spider_training.incline_press.ceil%> кг.</div>
    </div>
    <div class="row row-cols-4 my-3 center">
      <div class="col">
        <button class="btn btn-outline-light" type="button" data-bs-toggle="collapse"
              data-bs-target="#collapseText2" aria-expanded="false"
              aria-controls="collapseText2"><%= t('activerecord.attributes.spider.push_ups_on_bars') %>
        </button>
        <div class="collapse my-2" id="collapseText2">
          <span>
            <%= image_tag('Отжимания на брусьях.jpeg') %>
            <ul>
              <li>Запрыгните на брусья и опустите плечи.</li>
              <li>Следите, чтобы плечи не поднимались на протяжении всего упражнения.</li>
              <li>Выпрямите руки, но не блокируйте локтевой сустав.</li>
              <li>Опуститесь вниз до параллели плеч с полом.</li>
              <li>Следите, чтобы локти уходили назад, а не в стороны.</li>
            </ul>
          </span>
        </div>
      </div>
      <div class="col">4</div>
      <div class="col"><%= current_spider_training.monday_reps %></div>
      <div class="col"><%= current_spider_training.push_ups_on_bars.ceil%> кг.</div>
    </div>
    <div class="row row-cols-4 my-3 center">
      <div class="col">
        <button class="btn btn-outline-light" type="button" data-bs-toggle="collapse"
              data-bs-target="#collapseText3" aria-expanded="false"
              aria-controls="collapseText3"><%= t('activerecord.attributes.spider.close_grip_bench_press') %>
        </button>
          <div class="collapse my-2" id="collapseText3">
            <span>
              <%= image_tag('Жим лежа узким хватом.jpeg') %>
              <ul>
                <li>Лягте на скамью.</li>
                <li>Слегка прогнитесь в пояснице, но при этом убедитесь, что голова, плечи и ягодицы плотно прижаты к скамье.</li>
                <li>Возьмитесь за гриф хватом сверху. Расстояние между ладонями должно быть меньше ширины плеч.</li>
                <li>Выжмите штангу вверх и полностью выпрямите руки.</li>
                <li>Гриф должен оказаться точно над шеей.</li>
                <li>Сделайте глубокий вдох и, задержав дыхание, опустите штангу к нижней части грудной клетки.</li>
                <li>Едва гриф коснется груди, не останавливайтесь, а тут же начинайте жать штангу вверх.</li>
                <li>Как только руки будут полностью выпрямлены (верхняя точка упражнения), сделайте небольшую паузу и постарайтесь как можно сильнее напрячь трицепсы.</li>
              </ul>
            </span>
        </div>
      </div>
      <div class="col">4</div>
      <div class="col"><%= current_spider_training.monday_reps %></div>
      <div class="col"><%= current_spider_training.close_grip_bench_press.ceil%> кг.</div>
    </div>
    <div class="row row-cols-4 my-3 center">
      <div class="col">
        <button class="btn btn-outline-light" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapseText4" aria-expanded="false"
                aria-controls="collapseText4"><%= t('activerecord.attributes.spider.seated_dumbbell_press') %>
        </button>
        <div class="collapse my-2" id="collapseText4">
          <span>
            <%= image_tag('жим гантелей сидя.jpeg') %>
            <ul>
              <li>Установите спинку скамьи вертикально.</li>
              <li>Сядьте на скамью, возьмите в обе руки гантели и поднимите их над плечами.</li>
              <li>Чуть-чуть подайте гантели вперед и разверните так, чтобы ладони были направлены вперед.</li>
              <li>Отведите плечи назад и расправьте грудь.</li>
              <li>Сделайте вдох и, задержав дыхание, напрягите дельты и выжмите гантели по широкой дуге вверх.</li>
              <li>В верхней точке гантели почти касаются друг друга, руки полностью выпрямлены, а плечи приподняты.</li>
              <li>Плавно опустите гантели по той же траектории к плечам и приступайте к следующему повторению.</li>
            </ul>
          </span>
        </div>
      </div>
      <div class="col">4</div>
      <div class="col"><%= current_spider_training.monday_reps %></div>
      <div class="col"><%= current_spider_training.seated_dumbbell_press.ceil%> кг.</div>
    </div>
    <div class="row row-cols-4 my-3 center">
      <div class="col">
        <button class="btn btn-outline-light" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapseText5" aria-expanded="false"
                aria-controls="collapseText5"><%= t('activerecord.attributes.spider.barbell_pull_to_chin') %>
        </button>
        <div class="collapse my-2" id="collapseText5">
          <span>
          <%= image_tag('Тяга штанги к подбородку.jpeg') %>
            <ul>
              <li>Держите штангу верхним хватом (промежуток между ладонями немного меньше ширины плеч) и выровняйтесь.</li>
              <li>В исходном положении спина прямая и чуть прогнута в пояснице, плечи расправлены, руки в локтях ровные, гриф слегка касается бедер.</li>
              <li>Вдохните и, задержав дыхание, напрягите дельту и трапецепидную.</li>
              <li>Разведите локти и потяните их вверх вертикально.</li>
              <li>Движение «направляют» именно локти, а не предплечья или плечи.</li>
              <li>Когда вы поднимаете локти вверх, гриф штанги должен двигаться в вертикальной плоскости в длину тела от подбородка до бедер.</li>
              <li>Не нависайте над грифом, прогибая спину.</li>
              <li>Держите тело и шею прямо, а подбородок — горизонтально.</li>
              <li>В верхней точке локти находятся максимально вверху.</li>
              <li>Дотянувшись до верхней точки, сделайте выдох, остановитесь и еще больше напрягите дельты и трапеции.</li>
              <li>Медленно опустите гриф в исходное положение.</li>
            </ul>
          </span>
        </div>
      </div>
      <div class="col">4</div>
      <div class="col"><%= current_spider_training.monday_reps %></div>
      <div class="col"><%= current_spider_training.barbell_pull_to_chin.ceil%> кг.</div>
    </div>

    <div class="row row-cols-2 my-5">
      <div class="col left">
        <%= link_to t('global.button.fail'), user_update_spider_path(@user, @spider, complete_training: 'fail'), method: :put,
          class: 'btn btn-danger btn-lg'%></div>

      <div class="col right"><%= link_to t('global.button.complete'), user_update_spider_path(@user, @spider, complete_training: 'monday'), method: :put,
        class: 'btn btn-success btn-lg'%></div>
    </div>
    

app/views/spiders/_train.html.erb
<div class="progress">
  <div class="progress-bar bg-dark progress-bar-striped progress-bar-animated" role="progressbar"
       style="width: <%= current_spider_training.count_update_training * 2%>%"
       aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">
       <%= current_spider_training.count_update_training * 2%>%
  </div>
</div>

<div class="dropdown center my-3">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
    <%= t('global.dropdown.change_training')%>
  </button>
  <ul class="dropdown-menu">
    <li>
      <%= link_to t('global.dropdown.monday'), user_spider_path(@user, @spider, day: 'monday'),
        class: 'dropdown-item'%>
    </li>

    <li><hr class="dropdown-divider"></li>

    <li>
      <%= link_to t('global.dropdown.wednesday'), user_spider_path(@user, @spider, day: 'wednesday'),
        class: 'dropdown-item'%>
    </li>

    <li><hr class="dropdown-divider"></li>

    <li>
      <%= link_to t('global.dropdown.friday'), user_spider_path(@user, @spider, day: 'friday'),
        class: 'dropdown-item'%>
    </li>
  </ul>
</div>

<% case params[:day] %>
  <% when 'monday'%>
    <%= render 'monday' %>
  <% when 'wednesday'%>
    <%= render 'wednesday' %>
  <% when 'friday' %>
    <%= render 'friday' %>
<% end %>

app/views/spiders/new.html.erb
<% provide :page_title, t('crossfits.new.title') %>
<% currently_at t('crossfits.new.title') %>

<h1 class="mb-4 center">Spider</h1>

<%= render 'form' %>

app/views/spiders/show.html.erb
<% provide :page_title, t('.title') %>
<% currently_at t('menu.spider') %>

<body class="my-black-fon", style="color:#ffffff">

  <h1 class="center", style="color:#ffffff"><%= t('menu.spider')%></h1>
  <%= render 'train'%>
</body>