config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

class AdminConstraint
  def matches?(request)
    user_id = request.session[:user_id] || request.cookie_jar.encrypted[:user_id]

    User.find_by(id: user_id)&.admin_role?
  end
end

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    resource :session, only: %i[new create destroy]

    resource :password_reset, only: %i[new create edit update]

    resources :users, only: %i[new create edit update show] do
      resources :powers, except: %i[index]
      put '/powers/:id/update_power', to: 'powers#update_power', as: 'update_power'
      resources :crossfits, except: %i[index]
      put '/crossfits/:id/update_crossfit', to: 'crossfits#update_crossfit', as: 'update_crossfit'
      resources :gains, except: %i[index]
      put '/gains/:id/update_gain', to: 'gains#update_gain', as: 'update_gain'
      resources :photos, only: %i[index new create]
      resources :batmen, except: %i[index]
      put '/batmen/:id/update_batman', to: 'batmen#update_batman', as: 'update_batman'
      resources :wolverines, except: %i[index]
      put '/wolverines/:id/update_wolverine', to: 'wolverines#update_wolverine', as: 'update_wolverine'
      resources :spiders, except: %i[index]
      put '/spiders/:id/update_spider', to: 'spiders#update_spider', as: 'update_spider'
    end

    get '/faq', to: 'pages#faq'
    get '/training', to: 'pages#training'

    namespace :admin do
      resources :users, only: %i[index create edit update destroy]
    end
    root 'pages#index'
  end
end

app/models/crossfit.rb
# frozen_string_literal: true

class Crossfit < ApplicationRecord
  belongs_to :user

  validates :front_squat, presence: true
  validates :hang_grab, presence: true
  validates :overhead_press, presence: true
  validates :kettlebell_swing, presence: true
  validates :kettlebell_pull_to_the_chin, presence: true
  validates :russian_twist, presence: true
  validates :plank_with_kettlebell_pull, presence: true
  validates :trusters, presence: true
  validates :bent_over_barbell_pull, presence: true
  validates :deadlift, presence: true
  validates :mahi_dumbbells_through_the_sides, presence: true
  validates :dumbbell_layout, presence: true
  validates :barbell_pull_to_chin, presence: true
  validates :forearm_curls_and_press_ups_with_a_barbell, presence: true
  validates :cross_over, presence: true
  validates :abduction_in_a_butterfly, presence: true
  validates :lying_leg_flexion, presence: true
  validates :seated_leg_extension, presence: true
  validates :sumo_squats, presence: true
  validates :farm_walk, presence: true
end

app/controllers/crossfits_controller.rb
# frozen_string_literal: true

class CrossfitsController < ApplicationController
  before_action :set_user
  before_action :set_crossfit, except: %i[new create]

  def show; end

  def new
    @crossfit = @user.crossfits.build
  end

  def edit; end

  def create
    @crossfit = @user.crossfits.build crossfit_params
    if @crossfit.save
      flash[:success] = t('.success')
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def update
    if @crossfit.update crossfit_params
      flash[:success] = t('.success')
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def update_crossfit
    case params[:complete_training]
    when 'fail'
      flash[:success] = t('.fail')
    when 'monday'
      pump_crossfit_monday
      flash[:success] = t('.success')
    when 'wednesday'
      pump_crossfit_wednesday
      flash[:success] = t('.success')
    when 'friday'
      pump_crossfit_friday
      pump_count_update_crossfit_training
      flash[:success] = t('.success')
    end
    redirect_to root_path
  end

  def destroy
    @crossfit.destroy
    flash[:success] = t('.success')
    redirect_to user_path(@user)
  end

  private

  def set_user
    @user = User.find params[:user_id]
  end

  def set_crossfit
    @crossfit = @user.crossfits.find params[:id]
  end

  def crossfit_params
    params.require(:crossfit).permit(:front_squat, :hang_grab, :overhead_press, :kettlebell_swing,
                                     :kettlebell_pull_to_the_chin, :russian_twist, :plank_with_kettlebell_pull,
                                     :trusters, :bent_over_barbell_pull, :deadlift, :mahi_dumbbells_through_the_sides,
                                     :dumbbell_layout, :barbell_pull_to_chin, :forearm_curls_and_press_ups_with_a_barbell,
                                     :cross_over, :abduction_in_a_butterfly, :lying_leg_flexion, :seated_leg_extension,
                                     :sumo_squats, :farm_walk)
  end
end

app/views/crossfits/_friday.html.erb
<body style="color:#ffffff">

  <h2 class="my-4 center">
    <strong><%= t('views.first_block')%></strong>
  </h2>

  <div class="container my-4">
    <div class="row row-cols-5 center">
      <div class="col"><strong><%= t('views.exercise')%></strong></div>
      <div class="col"><strong><%= t('views.count_first_cycle')%></strong></div>
      <div class="col"><strong><%= t('views.count_second_cycle')%></strong></div>
      <div class="col"><strong><%= t('views.count_third_cycle')%></strong></div>
      <div class="col"><strong><%= t('views.weight')%></strong></div>
    </div>
    <div class="row row-cols-5 my-3 center">
      <div class="col">
        <button class="btn btn-outline-light" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapseText" aria-expanded="false"
                aria-controls="collapseText"><%= t('activerecord.attributes.crossfit.forearm_curls_and_press_ups_with_a_barbell') %>
        </button>
        <div class="collapse my-2" id="collapseText">
          <span>
            <%= image_tag('Сгибания предплечий со штангой.jpeg') %>
            <ul>
              <li>Первая часть движения аналогична Сгибаниям предплечий со штангой</li>
              <li>Вторая часть движения аналогична Жиму штанги над головой</li>
            </ul>
          </span>
        </div>
      </div>
      <div class="col">21</div>
      <div class="col">15</div>
      <div class="col">10</div>
      <div class="col"><%= current_crossfit_training.forearm_curls_and_press_ups_with_a_barbell.ceil%> кг.</div>
    </div>
    <div class="row row-cols-5 my-3 center">
      <div class="col">
        <button class="btn btn-outline-light" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapseText1" aria-expanded="false"
                aria-controls="collapseText1"><%= t('activerecord.attributes.crossfit.cross_over') %>
        </button>
        <div class="collapse my-2" id="collapseText1">
          <span>
            <%= image_tag('Кросс-овер.jpeg') %>
            <ul>
              <li>Установите блоки тренажера наверх.</li>
              <li>Сделайте небольшой шаг вперед, чтобы растянуть грудные.</li>
              <li>Ноги ставим на одну линию, если тяжело, то одну выводим вперед.</li>
              <li>Не забываем их чередовать каждый подход.</li>
              <li>Наклоняем туловище немного вперед.</li>
              <li>Спину держим ровной, в пояснице небольшой прогиб, грудь немного выставлена вперед.</li>
              <li>Руки разводим в стороны, пока не почувствуем растяжение грудных мышц.</li>
              <li>Локти при этом, немного согнуты.</li>
              <li>На выдохе начинаем сводить руки перед грудью, до касания ими друг друга.</li>
              <li>Задержитесь ненадолго в этом положении, что бы максимально напрячь грудь.</li>
              <li>На вдохе начинаем разводить руки в стороны до исходного положения, стараясь как можно сильней растянуть грудные мышцы.</li>
            </ul>
          </span>
        </div>
      </div>
      <div class="col">21</div>
      <div class="col">15</div>
      <div class="col">10</div>
      <div class="col"><%= current_crossfit_training.cross_over.ceil%> кг.</div>
    </div>
    <div class="row row-cols-5 my-3 center">
      <div class="col">
        <button class="btn btn-outline-light" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapseText2" aria-expanded="false"
                aria-controls="collapseText2"><%= t('activerecord.attributes.crossfit.abduction_in_a_butterfly') %>
        </button>
        <div class="collapse my-2" id="collapseText2">
          <span>
            <%= image_tag('Отведение в бабочке.jpeg') %>
            <ul>
              <li>Выставите высоту сидения так, чтобы рука отводилась назад в горизонтальной плоскости.</li>
              <li>Спинку тренажера отрегулируйте, чтобы она фиксировала положение корпуса.</li>
              <li>Садитесь в тренажер и возьмитесь за рукояти.</li>
              <li>Начинайте медленно разводить руки в стороны до тех пор, пока кисти не окажутся на одном уровне.</li>
              <li>Сделайте небольшую паузу и в медленном темпе вернитесь в исходную позицию.</li>
              <li>Не сводите рукояти вместе, чтобы сохранить напряжение в мышцах.</li>
            </ul>
          </span>
        </div>
      </div>
      <div class="col">21</div>
      <div class="col">15</div>
      <div class="col">10</div>
      <div class="col"><%= current_crossfit_training.abduction_in_a_butterfly.ceil%> кг.</div>
    </div>

  <h2 class="my-4 center">
    <strong><%= t('views.second_block')%></strong>
  </h2>

  <div class="container my-4">
    <div class="row row-cols-5 center">
      <div class="col"><strong><%= t('views.exercise')%></strong></div>
      <div class="col"><strong><%= t('views.count_first_cycle')%></strong></div>
      <div class="col"><strong><%= t('views.count_second_cycle')%></strong></div>
      <div class="col"><strong><%= t('views.count_third_cycle')%></strong></div>
      <div class="col"><strong><%= t('views.weight')%></strong></div>
    </div>
    <div class="row row-cols-5 my-3 center">
      <div class="col">
        <button class="btn btn-outline-light" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapseText3" aria-expanded="false"
                aria-controls="collapseText3"><%= t('activerecord.attributes.crossfit.lying_leg_flexion') %>
        </button>
        <div class="collapse my-2" id="collapseText3">
          <span>
            <%= image_tag('Сгибание голени лежа.jpeg') %>
            <ul>
              <li>Лягте на тренажер и заведите ноги под валик.</li>
              <li>Руками возьмитесь за специальные ручки или за края скамьи.</li>
              <li>На выдохе согните голени, стараясь максимально приблизить валик к ягодицам.</li>
              <li>Передняя поверхность бедер при этом прижата к скамье.</li>
              <li>На вдохе разгибайте голени, аккуратно опуская вес вниз.</li>
              <li>Полностью выпрямлять колени и расслаблять бицепс бедра в нижней точке не нужно.</li>
            </ul>
          </span>
        </div>
      </div>
      <div class="col">21</div>
      <div class="col">15</div>
      <div class="col">10</div>
      <div class="col"><%= current_crossfit_training.lying_leg_flexion.ceil%> кг.</div>
    </div>
    <div class="row row-cols-5 my-3 center">
      <div class="col">
        <button class="btn btn-outline-light" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapseText4" aria-expanded="false"
                aria-controls="collapseText4"><%= t('activerecord.attributes.crossfit.seated_leg_extension') %>
        </button>
        <div class="collapse my-2" id="collapseText4">
          <span>
            <%= image_tag('Разгибания голени сидя.jpeg') %>
            <ul>
              <li>Сядьте в тренажер, прижмитесь спиной к его спинке и заведите ноги за валик.</li>
              <li>Руками возьмитесь за специальные ручки по бокам от сиденья.</li>
              <li>Носки стоп поднимите вверх.</li>
              <li>На выдохе плавно разогните ноги в коленях.</li>
              <li>Максимально напрягите квадрицепсы в верхней точке, задержитесь в таком положении на 1–2 секунды.</li>
              <li>На вдохе подконтрольно опустите ноги вниз, но не сгибайте их до конца.</li>
              <li>То есть даже в нижней точке квадрицепсы должны быть напряжены.</li>
              <li>Следите за ощущениями в коленях, не бросайте резко ноги вниз.</li>
            </ul>
          </span>
        </div>
      </div>
      <div class="col">21</div>
      <div class="col">15</div>
      <div class="col">10</div>
      <div class="col"><%= current_crossfit_training.seated_leg_extension.ceil%> кг.</div>
    </div>
    <div class="row row-cols-5 my-3 center">
      <div class="col">
        <button class="btn btn-outline-light" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapseText5" aria-expanded="false"
                aria-controls="collapseText5"><%= t('activerecord.attributes.crossfit.jumping_lunges') %>
        </button>
        <div class="collapse my-2" id="collapseText5">
          <span>
            <%= image_tag('Выпады с выпрыгиванием.jpeg') %>
            <ul>
              <li>Встать в исходное положение для сплит-приседа.</li>
              <li>Выпрямить спину, подтянуть живот, отшагнуть одной ногой назад на расстояние полного шага.</li>
              <li>Вторую опорную оставить в обычном для приседания положении, носок чуть отведен в сторону.</li>
              <li>Опуститься в выпад до параллели рабочей ноги с полом.</li>
              <li>Выпрыгнуть их приседа вверх.</li>
            </ul>
          </span>
        </div>
      </div>
      <div class="col">21</div>
      <div class="col">15</div>
      <div class="col">10</div>
      <div class="col"><%= current_crossfit_training.jumping_lunges.ceil%> кг.</div>
    </div>

  <h2 class="my-4 center">
    <strong><%= t('views.third_block')%></strong>
  </h2>

  <div class="container my-4">
    <div class="row row-cols-5 center">
      <div class="col"><strong><%= t('views.exercise')%></strong></div>
      <div class="col"><strong><%= t('views.count_first_cycle')%></strong></div>
      <div class="col"><strong><%= t('views.count_second_cycle')%></strong></div>
      <div class="col"><strong><%= t('views.count_third_cycle')%></strong></div>
      <div class="col"><strong><%= t('views.weight')%></strong></div>
    </div>
    <div class="row row-cols-5 my-3 center">
      <div class="col">
        <button class="btn btn-outline-light" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapseText6" aria-expanded="false"
                aria-controls="collapseText6"><%= t('activerecord.attributes.crossfit.jumping_on_the_pedestal') %>
        </button>
        <div class="collapse my-2" id="collapseText6">
          <span>
            <%= image_tag('Запрыгивания на тумбу.jpeg') %>
            <ul>
              <li>Встаньте перед тумбой на расстоянии от 0,5 до 1 м. Ноги на ширине плеч.</li>
              <li>Это стартовая позиция. Чтобы прыгнуть, сядьте и махните руками назад.</li>
              <li>При прыжке на ящик поднимите колени и бедра как можно выше.</li>
              <li>В этом случае руки двигаются вперед и вверх.</li>
              <li>Вы должны приземлиться на обе ноги.</li>
              <li>Колени слегка согнуты.</li>
            </ul>
          </span>
        </div>
      </div>
      <div class="col">21</div>
      <div class="col">15</div>
      <div class="col">10</div>
      <div class="col"><%= current_crossfit_training.jumping_on_the_pedestal.ceil%> кг.</div>
    </div>
    <div class="row row-cols-5 my-3 center">
      <div class="col">
        <button class="btn btn-outline-light" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapseText6" aria-expanded="false"
                aria-controls="collapseText6"><%= t('activerecord.attributes.crossfit.sumo_squats') %>
        </button>
        <div class="collapse my-2" id="collapseText6">
          <span>
            <%= image_tag('Сумо приседания.jpeg') %>
            <ul>
              <li>Встаньте прямо, расставьте ноги шире, чем ширина плеч, а стопы разверните наружу под углом в 45 градусов.</li>
              <li>Взгляд направьте вперед, спина должна быть прямой, а грудь открытой.</li>
              <li>Начните опускаться вниз, сгибая колени и отклоняя таз назад, как будто хотите сесть на стул.</li>
            </ul>
          </span>
        </div>
      </div>
      <div class="col">21</div>
      <div class="col">15</div>
      <div class="col">10</div>
      <div class="col"><%= current_crossfit_training.sumo_squats.ceil%> кг.</div>
    </div>
    <div class="row row-cols-5 my-3 center">
      <div class="col">
        <button class="btn btn-outline-light" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapseText8" aria-expanded="false"
                aria-controls="collapseText8"><%= t('activerecord.attributes.crossfit.farm_walk') %>
        </button>
        <div class="collapse my-2" id="collapseText8">
          <span>
            <%= image_tag('Фермерская прогулка.jpeg') %>
            <ul>
              <li>Поясница прогнута, зафиксирована.</li>
              <li>Лопатки сведены.</li>
              <li>Руки «по швам».</li>
            </ul>
          </span>
        </div>
      </div>
      <div class="col">21</div>
      <div class="col">15</div>
      <div class="col">10</div>
      <div class="col"><%= current_crossfit_training.farm_walk.ceil%> кг.</div>
    </div> 

  <div class="row row-cols-2 my-5">
    <div class="col left">
      <%= link_to t('global.button.fail'), user_update_crossfit_path(@user, @crossfit, complete_training: 'fail'),
      method: :put, class: 'btn btn-danger btn-lg'%></div>

    <div class="col right">
      <%= link_to t('global.button.complete'), user_update_crossfit_path(@user, @crossfit, complete_training: 'friday'),
      method: :put, class: 'btn btn-success btn-lg'%></div>
  </div>
  
</body>

app/views/crossfits/_train.html.erb
<div class="progress">
  <div class="progress-bar bg-dark progress-bar-striped progress-bar-animated" role="progressbar"
       style="width: <%= current_crossfit_training.count_update_training * 2%>%"
       aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">
       <%= current_crossfit_training.count_update_training * 2%>%
  </div>
</div>

<div class="dropdown center my-3">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
    <%= t('global.dropdown.change_training')%>
  </button>
  <ul class="dropdown-menu">
    <li>
      <%= link_to t('global.dropdown.monday'), user_crossfit_path(@user, @crossfit, day: 'monday'),
        class: 'dropdown-item'%>
    </li>

    <li><hr class="dropdown-divider"></li>

    <li>
      <%= link_to t('global.dropdown.wednesday'), user_crossfit_path(@user, @crossfit, day: 'wednesday'),
        class: 'dropdown-item'%>
    </li>

    <li><hr class="dropdown-divider"></li>

    <li>
      <%= link_to t('global.dropdown.friday'), user_crossfit_path(@user, @crossfit, day: 'friday'),
        class: 'dropdown-item'%>
    </li>
  </ul>
</div>

<% case params[:day] %>
  <% when 'monday'%>
    <%= render 'monday' %>
  <% when 'wednesday'%>
    <%= render 'wednesday' %>
  <% when 'friday'%>
    <%= render 'friday' %>
<% end %>

app/views/crossfits/edit.html.erb
<% provide :page_title, t('crossfits.edit.title') %>
<% currently_at t('crossfits.edit.title') %>
<h1 class="mb-4 center"><%= t('crossfits.edit.title') %></h1>

<%= render 'form' %>

app/views/crossfits/new.html.erb
<% provide :page_title, t('crossfits.new.title') %>
<% currently_at t('crossfits.new.title') %>

<h1 class="mb-4 center"><%= t('crossfits.new.title') %></h1>

<%= render 'form' %>

app/views/crossfits/show.html.erb
<% provide :page_title, t('crossfits.show.title') %>
<% currently_at t('crossfits.show.title') %>

<body class="my-blue-fon">

  <h1 class="center", style="color:#ffffff"><%= t('crossfits.show.title')%></h1>
  <%= render 'train'%>
</body>