config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

class AdminConstraint
  def matches?(request)
    user_id = request.session[:user_id] || request.cookie_jar.encrypted[:user_id]

    User.find_by(id: user_id)&.admin_role?
  end
end

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    resource :session, only: %i[new create destroy]

    resource :password_reset, only: %i[new create edit update]

    resources :users, only: %i[new create edit update show] do
      resources :powers, except: %i[index]
      put '/powers/:id/update_power', to: 'powers#update_power', as: 'update_power'
      resources :crossfits, except: %i[index]
      put '/crossfits/:id/update_crossfit', to: 'crossfits#update_crossfit', as: 'update_crossfit'
      resources :gains, except: %i[index]
      put '/gains/:id/update_gain', to: 'gains#update_gain', as: 'update_gain'
      resources :photos, only: %i[index new create]
      resources :batmen, except: %i[index]
      put '/batmen/:id/update_batman', to: 'batmen#update_batman', as: 'update_batman'
      resources :wolverines, except: %i[index]
      put '/wolverines/:id/update_wolverine', to: 'wolverines#update_wolverine', as: 'update_wolverine'
      resources :spiders, except: %i[index]
      put '/spiders/:id/update_spider', to: 'spiders#update_spider', as: 'update_spider'
    end

    get '/faq', to: 'pages#faq'
    get '/training', to: 'pages#training'

    namespace :admin do
      resources :users, only: %i[index create edit update destroy]
    end
    root 'pages#index'
  end
end

app/views/shared/_errors.html.erb
<% if object.errors.full_messages.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_menu.html.erb
<%= provide :main_menu do %>
  <header class="p-3 bg-dark text-white">
    <div class="container">
      <nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><%= nav_tab t('menu.home'), root_path,
            class: 'nav-link px-2', current_page: current_page %></li>
            
            <% if policy([:admin, :user]).index? %>
            <li><%= nav_tab t('menu.users'), admin_users_path,
              class: 'nav-link px-2', current_page: current_page %></li>
          <% end %>

          <li><%= nav_tab t('menu.faq'), faq_path,
            class: 'nav-link px-2', current_page: current_page %></li>

          <% if user_signed_in? %>
          <li><%= nav_tab t('menu.create_traning'), training_path,
            class: 'nav-link px-2', current_page: current_page %></li>
          <% end %>
        </ul>

        <ul class="nav col-12 col-lg-auto mb-2 mb-md-0">
          <li class="dropdown">
            <%= link_to '#', class: 'nav-link px-2 dropdown-toggle text-white',
              data: {"bs-toggle": 'dropdown'} do %>
              <%= tag.div '', class: "flag #{I18n.locale}-flag mt-1" %>
              <%= t I18n.locale %>
            <% end %>
            
            <ul class="dropdown-menu">
              <% I18n.available_locales.each do |locale| %>
                <li>
                  <% if I18n.locale == locale %>
                    <%= tag.span t(locale), class: 'dropdown-item' %>
                  <% else %>
                    <%= link_to t(locale), root_path(locale: locale),
                      class: 'dropdown-item' %>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </li>
        </ul>

        <ul class="nav col-12 col-lg-auto mb-2 mb-md-0">
          <% if user_signed_in? %>
            <li class="dropdown">
              <%= link_to '#',
                class: 'nav-link px-2 dropdown-toggle text-white',
                data: {"bs-toggle": 'dropdown'} do %>
                <%= image_tag current_user.avatar.variant(resize_to_fill: [50, 50]), class: "rounded-image" %>
                <%= current_user.name_or_email %>
              <% end %>
              
              <ul class="dropdown-menu">
                <li>
                  <%= link_to t('menu.my_profile'), user_path(current_user),
                    class: 'dropdown-item' %>
                </li>

                <li><hr class="dropdown-divider"></li>

                <li>
                  <%= link_to t('menu.my_photo_diary'), user_photos_path(current_user),
                    class: 'dropdown-item' %>
                </li>

                <li><hr class="dropdown-divider"></li>

                <li>
                  <%= link_to t('users.edit.title'), edit_user_path(current_user),
                    class: 'dropdown-item' %>
                </li>

                <li><hr class="dropdown-divider"></li>

                <li>
                  <%= link_to t('menu.log_out'), session_path,
                    class: 'dropdown-item', data: {method: :delete} %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= nav_tab t('menu.sign_up'), new_user_path,
              class: 'nav-link px-2', current_page: current_page %></li>

            <li><%= nav_tab t('menu.log_in'), new_session_path,
              class: 'nav-link px-2', current_page: current_page %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>
<% end %>